### ISSUE TITLE
Uchiwa does not start

### ISSUE THREAD

**Issue by burgerbisquit** [sensu/uchiwa#328]
Uchiwa version: 0.8.1-1

Config:
```json
{
    "sensu": [
        {
            "name": "Sensu",
            "host": "hostname",
            "ssl": false,
            "port": 4567,
            "timeout": 5,
            "user": "admin",
            "pass": "secret",
            "path": ""
        }
    ],
    "uchiwa": {
        "host": "0.0.0.0",
        "port": 3000,
        "interval": 5,
        "user": "admin",
        "pass": "admin"
    }
}
```

```
cat /var/log/uchiwa.log
{"Date":"2015-05-19T02:10:01.45474602Z","Level":"info","Src":{"Func":"github.com/sensu/uchiwa/uchiwa.LoadConfig","Line":154},"Output":"Loading configuration file /etc/sensu/uchiwa.json"}
```

```
cat /var/log/uchiwa.err 
panic: interface conversion: interface is nil, not []interface {}

goroutine 20 [running]:
runtime.panic(0x6a0040, 0xc20805e500)
	/usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/sensu/uchiwa/uchiwa.BuildSubscriptions()
	/root/go/src/github.com/sensu/uchiwa/uchiwa/subscriptions.go:16 +0x142
github.com/sensu/uchiwa/uchiwa.Build(0x87c820)
	/root/go/src/github.com/sensu/uchiwa/uchiwa/dc.go:123 +0x2f2
github.com/sensu/uchiwa/uchiwa.Fetch(0xa)
	/root/go/src/github.com/sensu/uchiwa/uchiwa/dc.go:132 +0x2a
created by main.main
	/tmp/build/assets/opt/uchiwa/src/uchiwa.go:22 +0x1ba

goroutine 16 [runnable]:
math/big.nat.make(0xc2080e5d60, 0x10, 0x14, 0x11, 0x9, 0x9, 0x14)
	/usr/local/go/src/pkg/math/big/nat.go:69
math/big.nat.divLarge(0xc2080e5e00, 0x8, 0x14, 0xc2080e5d60, 0x10, 0x14, 0xc208039290, 0x10, 0x15, 0xc2080052c0, ...)
	/usr/local/go/src/pkg/math/big/nat.go:545 +0x4c0
math/big.nat.div(0xc2080e5e00, 0x8, 0x14, 0xc2080e5d60, 0x10, 0x14, 0xc208039290, 0x10, 0x15, 0xc2080052c0, ...)
	/usr/local/go/src/pkg/math/big/nat.go:519 +0x35c
math/big.nat.expNNWindowed(0xc208039290, 0x10, 0x15, 0xc208004ea0, 0x8, 0xc, 0xc208004de0, 0x8, 0xc, 0xc2080052c0, ...)
	/usr/local/go/src/pkg/math/big/nat.go:1351 +0x964
math/big.nat.expNN(0xc208004f00, 0x8, 0xc, 0xc208004ea0, 0x8, 0xc, 0xc208004de0, 0x8, 0xc, 0xc2080052c0, ...)
	/usr/local/go/src/pkg/math/big/nat.go:1260 +0x48d
math/big.nat.probablyPrime(0xc2080052c0, 0x8, 0xc, 0x14, 0xc)
	/usr/local/go/src/pkg/math/big/nat.go:1445 +0x839
math/big.(*Int).ProbablyPrime(0xc20803e020, 0x14, 0xc20803e0c0)
	/usr/local/go/src/pkg/math/big/int.go:722 +0x4a
crypto/rand.Prime(0x7f7d1798c440, 0xc208024420, 0x200, 0xc20803e020, 0x0, 0x0)
	/usr/local/go/src/pkg/crypto/rand/util.go:99 +0x44f
crypto/rsa.GenerateMultiPrimeKey(0x7f7d1798c440, 0xc208024420, 0x2, 0x400, 0xc2080043c0, 0x0, 0x0)
	/usr/local/go/src/pkg/crypto/rsa/rsa.go:168 +0x22c
crypto/rsa.GenerateKey(0x7f7d1798c440, 0xc208024420, 0x400, 0x10803ea60, 0x0, 0x0)
	/usr/local/go/src/pkg/crypto/rsa/rsa.go:126 +0x56
github.com/sensu/uchiwa/auth.initToken()
	/root/go/src/github.com/sensu/uchiwa/auth/token.go:27 +0x48
github.com/sensu/uchiwa/auth.(*Config).Simple(0x7f7d177edf30, 0xc208000c76, 0x5, 0xc208000c7b, 0x5)
	/root/go/src/github.com/sensu/uchiwa/auth/auth.go:48 +0x6e
main.main()
	/tmp/build/assets/opt/uchiwa/src/uchiwa.go:27 +0x2d3

goroutine 19 [finalizer wait]:
runtime.park(0x413320, 0x87b6d0, 0x879929)
	/usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x87b6d0, 0x879929)
	/usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 17 [syscall]:
runtime.goexit()
	/usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 23 [runnable]:
net/http.(*persistConn).readLoop(0xc208038790)
	/usr/local/go/src/pkg/net/http/transport.go:868 +0x829
created by net/http.(*Transport).dialConn
	/usr/local/go/src/pkg/net/http/transport.go:600 +0x93f

goroutine 24 [select]:
net/http.(*persistConn).writeLoop(0xc208038790)
	/usr/local/go/src/pkg/net/http/transport.go:885 +0x38f
created by net/http.(*Transport).dialConn
	/usr/local/go/src/pkg/net/http/transport.go:601 +0x957
```

**Comment by burgerbisquit** [comment]
False alarm, sorry.

**Comment by erulabs** [comment]
What was the solution to this @burgerbisquit ... Been trying to figure this out for a few hours now - cannot get Uchiwa 0.9 to start _at all_. If I supply a path of "/" it works correctly, but then 404's trying to reach sensu at "//127.0.0.1:4567//stashes\"... Any hints?

**Comment by burgerbisquit** [comment]
It's kinda weird, but it seems that my installation of uchiwa was using locally installed go packages, which led to my problem.
I had to remove them and reinstall uchiwa.
Hope this helps.
