### ISSUE TITLE
uchiwa 1.3.0 segfaults on unreachable sensu host

### ISSUE THREAD

**Issue by flowerysong** [sensu/uchiwa#786]
## Expected Behavior

In 1.2.0, when a datacenter is unavailable at startup uchiwa continues running instead of dying a horrible death.

## Current Behavior

uchiwa segfaults on startup. This being caused by the unreachable state is conjecture; I rolled back to uchiwa 1.2.0 without testing it with a reachable sensu server.

## Possible Solution

This is probably related to the new concurrency code.

## Steps to Reproduce (for bugs)
1.  `printf %s '{"sensu":[{"host":"example.com"}]}' > config.json`
2. `/opt/uchiwa/bin/uchiwa`

## Context

Example result:
```                                   
{"timestamp":"2018-06-07T21:23:44.15590985-04:00","level":"warn","message":"Loading the configuration file ./config.json"}
{"timestamp":"2018-06-07T21:23:44.156171262-04:00","level":"warn","message":"Sensu API  has no name property, make sure to set it in your configuration. Generating a temporary one..."}
{"timestamp":"2018-06-07T21:23:44.156272912-04:00","level":"warn","message":"Uchiwa is now listening on 0.0.0.0:3000"}
{"timestamp":"2018-06-07T21:23:44.156302772-04:00","level":"info","message":"Updating the datacenter sensu-81"}
{"timestamp":"2018-06-07T21:23:54.156557332-04:00","level":"warn","message":"GET http://example.com:4567/aggregates returned: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}
{"timestamp":"2018-06-07T21:23:54.156614154-04:00","level":"warn","message":"Connection failed to the datacenter sensu-81"}
{"timestamp":"2018-06-07T21:23:54.156829346-04:00","level":"warn","message":"GET http://example.com:4567/stashes returned: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}
{"timestamp":"2018-06-07T21:23:54.156843867-04:00","level":"warn","message":"Connection failed to the datacenter sensu-81"}
{"timestamp":"2018-06-07T21:23:54.156879255-04:00","level":"warn","message":"GET http://example.com:4567/silenced returned: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}
{"timestamp":"2018-06-07T21:23:54.156904616-04:00","level":"warn","message":"Impossible to retrieve silenced entries from the datacenter sensu-81. Silencing might not be possible, please update Sensu"}
{"timestamp":"2018-06-07T21:23:54.156951404-04:00","level":"warn","message":"GET http://example.com:4567/checks returned: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}
{"timestamp":"2018-06-07T21:23:54.156962154-04:00","level":"warn","message":"Connection failed to the datacenter sensu-81"}
{"timestamp":"2018-06-07T21:23:54.156982728-04:00","level":"warn","message":"GET http://example.com:4567/clients returned: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}
{"timestamp":"2018-06-07T21:23:54.156993319-04:00","level":"warn","message":"Connection failed to the datacenter sensu-81"}
{"timestamp":"2018-06-07T21:23:54.157037514-04:00","level":"warn","message":"GET http://example.com:4567/events returned: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}
{"timestamp":"2018-06-07T21:23:54.15704916-04:00","level":"warn","message":"Connection failed to the datacenter sensu-81"}
{"timestamp":"2018-06-07T21:23:54.157070358-04:00","level":"warn","message":"GET http://example.com:4567/info returned: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}
{"timestamp":"2018-06-07T21:23:54.157079723-04:00","level":"warn","message":"Connection failed to the datacenter sensu-81"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6d8969]

goroutine 24 [running]:
github.com/sensu/uchiwa/uchiwa/daemon.(*DatacenterSnapshotFetcher).fetchInfo(0xc4201360c0)
        /home/travis/gopath/src/github.com/sensu/uchiwa/uchiwa/daemon/daemon.go:313 +0x1b9
created by github.com/sensu/uchiwa/uchiwa/daemon.(*DatacenterFetcher).Fetch
        /home/travis/gopath/src/github.com/sensu/uchiwa/uchiwa/daemon/daemon.go:150 +0x3a4
```

## Your Environment

* Uchiwa version used: 1.3.0
* Operating System and version (e.g. Ubuntu 14.04): Amazon Linux 2 (2017.12)

**Comment by amdprophet** [comment]
Uchiwa 1.3.1 has been released with a fix for this issue.
